name: Documentation problem
description: Create a report to improve the browser guides, documentation, or other pages.
title: "Docs: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: textarea
    id: problem
    attributes:
      label: What should be added or corrected?
    validations:
      required: true